config/routes.rb
Rails.application.routes.draw do

  root to: 'main#index'
  get 'about', to: 'main#about'
  get 'contact', to: 'main#contact'
  get 'how-it-works', to: 'main#how'
  post 'contact', to: 'main#store_contact'

  get 'employee/register', to: 'employee#create'
  post 'employee/register', to: 'employee#store'
  get 'employee/login', to: 'login#create'
  post 'employee/login', to: 'login#store'
  get '/company/employee/email', to: 'update_email#edit'
  post '/company/employee/email', to: 'update_email#update'
  get '/company/employee/password', to: 'reset_password#edit'
  patch '/company/employee/password', to: 'reset_password#update'
  delete 'logout', to:'logout#destroy'
  get '/employee/forgot-password', to:'forgot_password#edit'
  post '/employee/forgot-password', to:'forgot_password#update'
  get 'reset/password', to:'forgot_password#change'
  post 'reset/password', to:'forgot_password#reset'

  get 'company/register', to: 'company#create'
  post 'company/register', to: 'company#store'
  get 'company/dashboard', to: 'customer#my'
  get 'company/clients/:id/show', to: 'client#show'
  get 'company/clients', to: 'client#index'
  get 'company/clients/register', to: 'client#create'
  post 'company/clients/register', to: 'client#store'
  get 'company/clients/:id/car/register', to: 'car#register'
  post 'company/clients/:id/car/register', to: 'car#store'
  post '/company/delete', to: 'car#delete'

  get 'company/car/:id/report/create', to: 'report#register'
  post 'company/car/:id/report/create', to: 'report#store'
  get 'company/accidents', to: 'report#index'
  post 'company/accidents/:id/delete', to: 'report#delete'
  get 'company/accidents/:id/show', to: 'report#show'
  get 'company/accidents/:id/edit', to: 'report#edit'
  post 'company/accidents/:id/edit', to: 'report#update'


end

app/controllers/reset_password_controller.rb
class ResetPasswordController < ApplicationController
  before_action :require_user_logged_in!
  before_action :get_user, only: [:edit, :update]

  def edit; end

  def update
    if params[:user][:password].empty? || params[:user][:current_password].empty?
      @user.errors.add(:password, 'provide all the fields')
      render 'edit'
    elsif @user.update_attributes(user_params)
      redirect_to company_dashboard_path, notice: 'Password update successfully '
    else
      render 'edit'
    end
  end

    private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def get_user
    @user = Current.user
  end
end

app/views/reset_password/edit.erb
<div class="container mt-4">
	<div class="columns">
		<div class="column is-one-quarter">
			<%= render partial: "partials/employee_nav" %>
		</div>
		<div class="column">
			<div class="card px-5 card_wrapper">
				<div class="card-content">
					<div class="content">
							<%= form_for(@user, url: company_employee_password_path(params[:id])) do |f| %>
							<% if @user.errors.any? %>
								<%@user.errors.full_messages.each do |message| %>
									<p class="help is-danger"><%= message %></p>
								<%end %>
							<%end %>
							<div class="field">
								<div class="field">
									<%= f.label :password,"Current Password",class: "label" %>
									<p class="control">
										<%= f.password_field :current_password, class: 'input' %>
									</p>
								</div>
							</div>
							<div class="field">
								<div class="field">
									<%= f.label :password,"New Password",class: "label" %>
									<p class="control">
										<%= f.password_field :password, class: 'input' %>
									</p>
								</div>
							</div>
							<div class="field">
								<%= f.label :password,"Confirmation",class: "label" %>
								<p class="control">
									<%= f.password_field :password_confirmation, class: 'input' %>
								</p>
							</div>
							<div class="field">
								<p class="control">
									<%= f.submit "Update password", class: "button is-primary" %>
								</p>
							</div>
							<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>