config/routes.rb
Rails.application.routes.draw do

  root to: 'main#index'
  get 'about', to: 'main#about'
  get 'contact', to: 'main#contact'
  get 'how-it-works', to: 'main#how'
  post 'contact', to: 'main#store_contact'

  get 'employee/register', to: 'employee#create'
  post 'employee/register', to: 'employee#store'
  get 'employee/login', to: 'login#create'
  post 'employee/login', to: 'login#store'
  get '/company/employee/email', to: 'update_email#edit'
  post '/company/employee/email', to: 'update_email#update'
  get '/company/employee/password', to: 'reset_password#edit'
  patch '/company/employee/password', to: 'reset_password#update'
  delete 'logout', to:'logout#destroy'
  get '/employee/forgot-password', to:'forgot_password#edit'
  post '/employee/forgot-password', to:'forgot_password#update'
  get 'reset/password', to:'forgot_password#change'
  post 'reset/password', to:'forgot_password#reset'

  get 'company/register', to: 'company#create'
  post 'company/register', to: 'company#store'
  get 'company/dashboard', to: 'customer#my'
  get 'company/clients/:id/show', to: 'client#show'
  get 'company/clients', to: 'client#index'
  get 'company/clients/register', to: 'client#create'
  post 'company/clients/register', to: 'client#store'
  get 'company/clients/:id/car/register', to: 'car#register'
  post 'company/clients/:id/car/register', to: 'car#store'
  post '/company/delete', to: 'car#delete'

  get 'company/car/:id/report/create', to: 'report#register'
  post 'company/car/:id/report/create', to: 'report#store'
  get 'company/accidents', to: 'report#index'
  post 'company/accidents/:id/delete', to: 'report#delete'
  get 'company/accidents/:id/show', to: 'report#show'
  get 'company/accidents/:id/edit', to: 'report#edit'
  post 'company/accidents/:id/edit', to: 'report#update'


end

app/views/partials/_employee_nav.erb
<div class="panel is-primary"  id="panel">
	<div class="panel-heading">
		Management
	</div>
	<a class="panel-block  has-text-weight-semibold" href="/company/dashboard">
					<span class="panel-icon">
							<i class="fas fa-columns"></i>
					</span>
		Dashboard
	</a>
	<a class="panel-block  has-text-weight-semibold" href="/company/clients/register">
					<span class="panel-icon">
							<i class="fas fa-user"></i>
					</span>
		      Add New Client
	</a>
	<a class="panel-block has-text-weight-semibold" href="/company/clients">
					<span class="panel-icon ">
							<i class="fas fa-users"></i>
					</span>
		      All Client
	</a>
	<a class="panel-block  has-text-weight-semibold" href="/company/accidents">
					<span class="panel-icon">
						<i class="fas fa-book" aria-hidden="true"></i>
					</span>
		      Accident Report
	</a>
	<a class="panel-block  has-text-weight-semibold" href="/company/employee/email">
					<span class="panel-icon">
						<i class="fas fa-mail-bulk"></i>
					</span>
	      	Change Email
	</a>

	<a class="panel-block  has-text-weight-semibold" href="/company/employee/password">
					<span class="panel-icon">
						<i class="fas fa-unlock-alt"></i>
					</span>
		      Reset Password
	</a>
	<a class="panel-block  has-text-weight-semibold" href="/logout">
					<span class="panel-icon">
						<i class="fas fa-sign-out-alt"></i>
					</span>
		      Sign out
	</a>
</div>

app/views/partials/_flash.erb
<% if flash[:alert] %>
<div class="notification is-danger flash">
	<button class="delete"></button>
	<%=flash[:alert] %>
</div>
<%end %>
<% if flash[:notice] %>
<div class="notification is-alert flash">
	<button class="delete"></button>
	<%=flash[:notice] %>
</div>
<%end %>

app/views/partials/_footer.erb
<footer class="footer">
	<div class="has-text-centered">
			<strong>Alinda © 2021</strong> by <a href="#">Carlos Barbier</a>. The source code is licensed
			<a href="#">MIT</a>. The website content
			is licensed <a href="#">CC BY NC SA 4.0</a>.
	</div>
</footer>

app/views/partials/_hero.erb
<div class="section hero_wrapper">
	<div class="container">
		<div class="columns ">
			<div class="column is-one-thirds">
				<div class="card call__action_card_wrapper is-radiusless">
					<div class="card-content is-flex-row is-justify-content-center is-align-content-center ">
							<p class="subtitle is-3">You take care of your <span class="customer">Business,</span></p>
							<p class="subtitle is-3">We take care of your <span class="business">System</span></p>
            <a href="/company/register"><button class="button is-primary btn__action"> Register Now</button> </a>
					</div>
				</div>

			</div>
			<div class="column image__hero is-two-thirds">
				<div class="contact_img_wrapper">
					<%= image_tag('undraw_towing_6yy4.png') %>
				</div>
			</div>
		</div>
	</div>

</div>

app/views/partials/_nav.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
				<%= image_tag('logo3.png') %>
      </a>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-end">
				<div class="navbar-start">
					<%= link_to "About" ,about_path ,class: "navbar-item" %>
					<%= link_to "How it works?",'/how-it-works'  ,class: "navbar-item" %>
					<%= link_to "Contact" ,contact_path ,class: "navbar-item" %>
				</div>
        <div class="navbar-item">
          <div class="buttons">
						<% if Current.user %>
							<div class="dropdown is-hoverable is-right">
								<div class="dropdown-trigger">
									<button class="button" aria-haspopup="true" aria-controls="dropdown-menu4">
								<span class="icon is-small">
									<span class="mr-1 ml-3"> <%= Current.user.name %></span>
								<i class="fas fa-angle-down" aria-hidden="true"></i>
							</span>
									</button>
								</div>
								<div class="dropdown-menu  " id="dropdown-menu" role="menu">
									<div class="dropdown-content">
										<div class="dropdown-item">
											<%= link_to "Dashboard" ,company_dashboard_path ,class: "dropdown-item" %>
											<%= link_to "Add New Client" ,company_clients_register_path ,class: "dropdown-item" %>
											<%= link_to "Clients" ,company_clients_path ,class: "dropdown-item" %>
											<%= link_to "Accidents Reports" ,company_accidents_path ,class: "dropdown-item" %>
											<%= link_to "Change Email" ,company_employee_email_path ,class: "dropdown-item" %>
											<%= link_to "Change Password" ,'/company/employee/password' ,class: "dropdown-item" %>
											<hr class="dropdown-divider">
											<%= button_to "Logout",logout_path,method: :delete,class: "button"%>
										</div>
									</div>
								</div>
							</div>
						<%else %>
							<%= link_to "Sign up" ,employee_register_path ,class: "button is-primary" %>
							<%= link_to "Log in" ,employee_login_path ,class: "button is-light" %>
						<%end %>

          </div>
        </div>
      </div>
    </div>
    </div>
  </div>

</nav>